[package]
name = "didwebvh-rs"
version = "0.1.13"
description = "Implementation of the did:webvh method in Rust"
repository = "https://github.com/decentralized-identity/didwebvh-rs"
edition = "2024"
authors = ["Glenn Gore <glenn@affinidi.com>"]
homepage = "https://didwebvh.info/"
keywords = ["ssi"]
publish = true
license = "Apache-2.0"
readme = "README.md"
rust-version = "1.88.0"

[features]
default = []
ssi = ["dep:ssi"]

[dependencies]
affinidi-data-integrity = { version = "0.3" }
affinidi-secrets-resolver = "0.4"

ahash = { version = "0.8", features = ["serde"] }
base58 = "0.2"
chrono = { version = "0.4", features = ["serde"] }
multihash = "0.19"
regex = "1.12"
reqwest = "0.12"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_json_canonicalizer = "0.3.1"
serde_with = "3.16"
sha2 = "0.10"
ssi = { version = "0.12", features = ["secp384r1"], optional = true }
thiserror = "2.0"
tokio = { version = "1.48" }
tracing = { version = "0.1" }
url = "2.5"
getrandom = { version = "0.3", features = ["wasm_js"] }

[dev-dependencies]
affinidi-tdk = "0.2"

anyhow = "1.0"
byte-unit = "5.2"
clap = { version = "4.5", features = ["derive"] }
console = "0.16"
dialoguer = "0.12"
format_num = "0.1.0"
rand = "0.9"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "fmt",
  "json",
  "valuable",
] }
